routes/web.php
<?php

// use App\Http\Controllers\ProfileController;
// use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');

// Route::middleware('auth')->group(function () {
//     Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
//     Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
//     Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
// });

// require __DIR__.'/auth.php';


use App\Http\Controllers\Backend\Auth\AdminLoginController;
use App\Http\Controllers\Backend\Auth\AdminRegistrationController;
use App\Http\Controllers\Backend\BannerCollectionController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\ColorController;
use App\Http\Controllers\Backend\CompanyInfoController;
use App\Http\Controllers\Backend\CouponController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\FlashSaleController;
use App\Http\Controllers\Backend\GeneralController;
use App\Http\Controllers\Backend\MainMenu\CategoryController;
use App\Http\Controllers\Backend\MainMenu\ChildcategoryController;
use App\Http\Controllers\Backend\MainMenu\SubcategoryController;
use App\Http\Controllers\Backend\PageController;
use App\Http\Controllers\Backend\ProductCollectionController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\ShippingChargeController;
use App\Http\Controllers\Backend\SizeController;
use App\Http\Controllers\Backend\SliderController;
use App\Http\Controllers\Backend\VoucherController;
use App\Http\Controllers\Common\OrderController;
use App\Http\Controllers\Common\RatingReviewController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\FrontendController;
use App\Http\Controllers\Frontend\ProfileController;
use App\Http\Controllers\Frontend\WishlistController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::controller(FrontendController::class)->group(function () {
    Route::get('/', 'index')->name('home');
    Route::get('/categories', 'category')->name('category');
    Route::get('/fashion_categor', 'fashionCategory')->name('fashionCategory');
    Route::get('/voucher', 'voucher')->name('voucher');
    Route::get('/product/{product}', 'productDetails')->name('productDetails');
    Route::get('/page/{slug}', 'page')->name('page');
    Route::get('/search/', 'search')->name('search');
    Route::get('/f/{category}/{sub?}/{child?}', 'categoryProduct')->name('categoryProduct');

    //offer
    Route::get('/banner/collection/{id}', 'bannerCollectionProduct')->name('bannerCollectionProduct');
    Route::get('/all-mall-product', 'allMallProduct')->name('allMallProduct');
    Route::get('/mall/collection/{id}', 'mallProduct')->name('mallProduct');
    Route::get('/all-product/all-collection', 'allCollection')->name('allCollection');
    Route::get('/all-product/collection/{id}', 'allProductCollection')->name('allProductCollection');

    Route::get('/flash-deal', 'allFlashDealProduct')->name('allFlashDealProduct');
    Route::get('/everyday-low-price', 'allEverydayLowPriceProduct')->name('allEverydayLowPriceProduct');
    Route::get('/flash-sale', 'allFlashSaleProduct')->name('allFlashSaleProduct');
    Route::get('/fashion', 'allFashionProduct')->name('allFashionProduct');
    Route::get('/order-track','orderTrack')->name('order.track');
    Route::post('/order-track','orderTrackStore');
});

Route::controller(CartController::class)->group(function () {
    //cart
    Route::get('/cart', 'cart')->name('cart');
    Route::post('/add-to-cart', 'addToCart');
    Route::post('/update-cart', 'updateCart')->name('updateCart');
    Route::get('/remove-from-cart/{rowId}', 'removeFromCart')->name('removeFromCart');
    Route::get('/destroy-cart', 'destroyCart')->name('destroyCart');

    //coupon
    Route::post('/apply-coupon', 'applyCoupon')->name('applyCoupon');
    Route::get('/remove-coupon', 'removeCoupon')->name('removeCoupon');
});
Route::post('/add-to-wishlist', [WishlistController::class, 'addToWishlist']);
Route::post('/add-voucher', [CartController::class, 'applyVoucher']);
Route::middleware('auth')->group(function () {
    //rating and review
    Route::post('/store-rating-review', [RatingReviewController::class, 'storeRatingReview'])->name('storeRatingReview');
    //user dashboard
    Route::get('/user/dashboard', [FrontendController::class, 'dashboard'])->name('user.dashboard');

    //wishlist
    Route::get('/wishlist', [WishlistController::class, 'wishlist'])->name('wishlist');

    Route::get('/remove-from-wishlist/{id}', [WishlistController::class, 'removeFromWishlist'])->name('removeFromWishlist');

    //user profile
    Route::get('/user-profile', [ProfileController::class, 'showProfile'])->name('showProfile');
    Route::post('/store-user-profile/{id}', [ProfileController::class, 'storeProfile'])->name('storeProfile');

    //checkout
    Route::get('/checkout', [CheckoutController::class, 'checkout'])->name('checkout');

    //adding shipping charge by ajax request
    Route::post('/add-shipping-charge', [CartController::class, 'addshippingCharge']);

    //place order
    Route::post('/place-order', [OrderController::class, 'placeOrder'])->name('placeOrder');
    Route::get('/order-history', [OrderController::class, 'customerOrderHistory'])->name('orderHistory');
    Route::post('/cancel-order/{id}', [OrderController::class, 'customerCancelOrder'])->name('cancelOrder');
    Route::get('/user-invoice/{id}', [OrderController::class, 'customerInvoice'])->name('invoice');

});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

//backend
Route::prefix('/admin')->name('admin.')->middleware('guest:admin')->group(function () {
    Route::get('/login', [AdminLoginController::class, 'login'])->name('login');
    Route::post('/store-login', [AdminLoginController::class, 'storeLogin'])->name('storeLogin');
});

Route::prefix('/admin')->as('admin.')->middleware('auth:admin')->group(function () {
    Route::post('/logout', [AdminLoginController::class, 'logout'])->name('logout');

    Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');

    //admin management
    Route::controller(AdminRegistrationController::class)->middleware('admin_user')->group(function () {
        Route::get('/admin-list', 'adminList')->name('adminList');
        Route::get('/create-admin', 'createAdmin')->name('createAdmin');
        Route::post('/store-admin', 'storeAdmin')->name('storeAdmin');
        Route::get('/edit-admin/{admin}', 'editAdmin')->name('editAdmin');
        Route::post('/update-admin/{admin}', 'updateAdmin')->name('updateAdmin');
        Route::post('/admin/active-admin/{admin}', 'activeAdmin')->name('activeAdmin');
        Route::post('/admin/inactive-admin/{admin}', 'inactiveAdmin')->name('inactiveAdmin');
        Route::delete('/delete-admin/{admin}', 'deleteAdmin')->name('deleteAdmin');

        Route::get('/customer-list', 'customerList')->name('customerList');
    });
    Route::middleware('main_menu')->group(function () {
        //slider
        Route::controller(SliderController::class)->group(function () {
            Route::get('/slider', 'allSlider')->name('allSlider');
            Route::get('/create-slider', 'createSlider')->name('createSlider');
            Route::post('/store-slider', 'storeSlider')->name('storeSlider');
            Route::get('/edit-slider/{slider}', 'editSlider')->name('editSlider');
            Route::put('/update-slider/{slider}', 'updateSlider')->name('updateSlider');
            Route::delete('/delete-slider/{slider}', 'deleteSlider')->name('deleteSlider');
        });

        //main menu
        //category
        Route::controller(CategoryController::class)->group(function () {
            Route::get('/category', 'category')->name('category');
            Route::get('/create-category', 'createCategory')->name('createCategory');
            Route::post('/store-category', 'storeCategory')->name('storeCategory');
            Route::get('/edit-category/{id}', 'editCategory')->name('editCategory');
            Route::patch('/update-category/{id}', 'updateCategory')->name('updateCategory');
            Route::post('/active-category/{id}', 'activeCategory')->name('activeCategory');
            Route::post('/inactive-category/{id}', 'inactiveCategory')->name('inactiveCategory');
        });

        //subcategory
        Route::controller(SubcategoryController::class)->group(function () {
            Route::get('/subcategory', 'subcategory')->name('subcategory');
            Route::get('/create-subcategory', 'createSubcategory')->name('createSubcategory');
            Route::post('/store-subcategory', 'storeSubcategory')->name('storeSubcategory');

app/Models/Subcategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Subcategory extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function category() {
        return $this->belongsTo(Category::class);
    }

    public function childcategories() {
        return $this->hasMany(Childcategory::class);
    }

    public function products() {
        return $this->hasMany(Product::class);
    }

    public function setNameAttribute($value) {
        $this->attributes['name'] = $value;
        $this->attributes['slug'] = Str::slug($value);
    }

    public function getIsActiveAttribute() {
        return $this->status === 1 ? 'Active' : 'Inactive';
    }
}

app/Http/Controllers/Backend/MainMenu/CategoryController.php
<?php

namespace App\Http\Controllers\Backend\MainMenu;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    public function category() {
        $categories = Category::withCount('subcategories')->get();

        return view('backend.main_menu.category.index', compact('categories'));
    }

    public function createCategory() {
        return view('backend.main_menu.category.create');
    }

    public function storeCategory(Request $request) {
        $validator = Validator::make($request->all(), [
            'icon'  => 'required',
            'name'  => 'required|unique:categories',
            'image' => 'required|image|mimes:jpeg,png,jpg,webp,gif',
        ]);

        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all())->withInput();
        }

        if ($request->hasFile('image')) {

            $image_file = $request->file('image');

            if ($image_file) {

                $img_gen   = hexdec(uniqid());
                $image_url = 'images/main_menu/category/';
                $image_ext = strtolower($image_file->getClientOriginalExtension());

                $img_name    = $img_gen . '.' . $image_ext;
                $final_name1 = $image_url . $img_gen . '.' . $image_ext;

                $image_file->move($image_url, $img_name);
            }

        }

        $category          = new Category();
        $category->icon    = $request->icon;
        $category->name    = $request->name;
        $category->status  = 1;
        $category->image   = $final_name1;
        $category->save();

        return redirect()->route('admin.category')->withToastSuccess('Category added successfully!!');
    }

    public function editCategory($id) {
        $category = Category::where('id', $id)->first();

        return view('backend.main_menu.category.edit', compact('category'));
    }

    public function updateCategory(Request $request, $id) {
        $validator = Validator::make($request->all(), [
            'icon'  => 'required',
            'name'  => 'required|unique:categories,name,' . $id,
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif',
        ]);

        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all())->withInput();
        }

        $category = Category::findOrFail($id);

        if ($request->hasFile('image')) {

            $image_file = $request->file('image');

            if ($image_file) {

                $image_path = public_path($category->image);

                if (File::exists($image_path)) {
                    File::delete($image_path);
                }

                $img_gen   = hexdec(uniqid());
                $image_url = 'images/main_menu/category/';
                $image_ext = strtolower($image_file->getClientOriginalExtension());

                $img_name    = $img_gen . '.' . $image_ext;
                $final_name1 = $image_url . $img_gen . '.' . $image_ext;

                $image_file->move($image_url, $img_name);
                $category->update(
                    [
                        'image' => $final_name1,
                    ]
                );
            }

        }

        $category->update([
            'icon'    => $request->icon,
            'name'    => $request->name,
        ]);

        return redirect()->route('admin.category')->withToastSuccess('Category updated successfully!!');
    }

    public function activeCategory(Request $request, $id) {
        $category = Category::findOrFail($id);

        $category->status = 1;
        $category->save();

        return redirect()->route('admin.category')->withToastSuccess('Category activated successfully!!');
    }

    public function inactiveCategory(Request $request, $id) {
        $category = Category::findOrFail($id);

        $category->status = 0;
        $category->save();

        return redirect()->route('admin.category')->withToastSuccess('Category inactivated successfully!!');
    }

}

resources/views/backend/main_menu/subcategory/create.blade.php
@extends('backend.layouts.master')
@section('title', 'Add Subcategory')

@section('backend')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Subcategory</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active">Add Subcategory</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form action="{{ route('admin.storeSubcategory') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Category</label>
                                            <select class="form-control select2bs4" style="width: 100%;" name="category_id" required>
                                                <option>==Select Category==</option>
                                                @foreach ($categories as $category)
                                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Name</label>
                                            <input type="text" class="form-control" id="exampleInputEmail1"
                                                value="{{ old('name') }}" placeholder="Enter category name" name="name">
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputFile">Category Image(80x80)</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="image" id="exampleInputFile">
                                            <label class="custom-file-label" for="exampleInputFile">Choose
                                                file</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/backend/main_menu/subcategory/edit.blade.php
@extends('backend.layouts.master')
@section('title', 'Edit Subcategory')

@section('backend')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Subcategory</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active">Edit Subcategory</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form action="{{ route('admin.updateSubcategory', $subcategory) }}" method="POST"
                            enctype="multipart/form-data">
                            @csrf
                            @method('patch')
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Category</label>
                                            <select class="form-control select2bs4" name="category_id" style="width: 100%;">
                                                @foreach ($categories as $category)
                                                    <option value="{{ $category->id }}"
                                                        @if ($subcategory->category_id === $category->id) {{ 'selected' }} @endif>
                                                        {{ $category->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Name</label>
                                            <input type="text" class="form-control" id="exampleInputEmail1"
                                                value="{{ $subcategory->name }}" placeholder="Enter category name" name="name">
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputFile">Subcategory Image(80x80)</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="image" id="exampleInputFile">
                                            <label class="custom-file-label" for="exampleInputFile">Choose
                                                file</label>
                                        </div>
                                    </div>
                                    @if (!empty($subcategory->image))
                                        <img src="{{ asset($subcategory->image) }}" height="80" width="80" alt="">
                                    @endif
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/backend/main_menu/subcategory/index.blade.php
@extends('backend.layouts.master')
@section('title', 'Subcategory')

@section('backend')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Main Subcategory List</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active">Subcategory</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">
                            <a href="{{ route('admin.createSubcategory') }}" class="btn btn-outline-primary">Add Subcategory</a>
                            <br>
                            <br>
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Action</th>
                                        <th>Name</th>
                                        <th>Category</th>
                                        <th>Status</th>
                                        <th>Image</th>
                                        <th>Created_at</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($subcategories as $subcategory)
                                        <tr>
                                            <td class="d-flex justify-content-between">
                                                <a href="{{ route('admin.editSubcategory', $subcategory) }}"
                                                    class="btn btn-info btn-xs"> <i class="fas fa-edit"></i> </a>
                                                @if ($subcategory->status === 1)
                                                    <form action="{{ route('admin.inactiveSubcategory', $subcategory) }}"
                                                        method="post">
                                                        @csrf
                                                        <button type="submit"
                                                            onclick="return(confirm('Are you sure want to INACTIVE this item?'))"
                                                            class="btn btn-danger btn-xs"> <i
                                                                class="far fa-thumbs-down"></i>
                                                        </button>
                                                    </form>
                                                @else
                                                    <form action="{{ route('admin.activeSubcategory', $subcategory) }}"
                                                        method="post">
                                                        @csrf
                                                        <button type="submit"
                                                            onclick="return(confirm('Are you sure want to Active this item?'))"
                                                            class="btn btn-info btn-xs"> <i class="far fa-thumbs-up"></i>
                                                        </button>
                                                    </form>
                                                @endif
                                            </td>
                                            <td>{{ $subcategory->name }}</td>
                                            <td>{{ $subcategory->category->name??'' }}</td>
                                            <td>{{ $subcategory->is_active }}</td>
                                            <td><img src="{{ asset($subcategory->image) }}" height="50" width="50"></td>
                                            <td>{{ $subcategory->created_at }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection