routes/web.php
<?php

// use App\Http\Controllers\ProfileController;
// use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');

// Route::middleware('auth')->group(function () {
//     Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
//     Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
//     Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
// });

// require __DIR__.'/auth.php';


use App\Http\Controllers\Backend\Auth\AdminLoginController;
use App\Http\Controllers\Backend\Auth\AdminRegistrationController;
use App\Http\Controllers\Backend\BannerCollectionController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\ColorController;
use App\Http\Controllers\Backend\CompanyInfoController;
use App\Http\Controllers\Backend\CouponController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\FlashSaleController;
use App\Http\Controllers\Backend\GeneralController;
use App\Http\Controllers\Backend\MainMenu\CategoryController;
use App\Http\Controllers\Backend\MainMenu\ChildcategoryController;
use App\Http\Controllers\Backend\MainMenu\SubcategoryController;
use App\Http\Controllers\Backend\PageController;
use App\Http\Controllers\Backend\ProductCollectionController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\ShippingChargeController;
use App\Http\Controllers\Backend\SizeController;
use App\Http\Controllers\Backend\SliderController;
use App\Http\Controllers\Backend\VoucherController;
use App\Http\Controllers\Common\OrderController;
use App\Http\Controllers\Common\RatingReviewController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\FrontendController;
use App\Http\Controllers\Frontend\ProfileController;
use App\Http\Controllers\Frontend\WishlistController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::controller(FrontendController::class)->group(function () {
    Route::get('/', 'index')->name('home');
    Route::get('/categories', 'category')->name('category');
    Route::get('/fashion_categor', 'fashionCategory')->name('fashionCategory');
    Route::get('/voucher', 'voucher')->name('voucher');
    Route::get('/product/{product}', 'productDetails')->name('productDetails');
    Route::get('/page/{slug}', 'page')->name('page');
    Route::get('/search/', 'search')->name('search');
    Route::get('/f/{category}/{sub?}/{child?}', 'categoryProduct')->name('categoryProduct');

    //offer
    Route::get('/banner/collection/{id}', 'bannerCollectionProduct')->name('bannerCollectionProduct');
    Route::get('/all-mall-product', 'allMallProduct')->name('allMallProduct');
    Route::get('/mall/collection/{id}', 'mallProduct')->name('mallProduct');
    Route::get('/all-product/all-collection', 'allCollection')->name('allCollection');
    Route::get('/all-product/collection/{id}', 'allProductCollection')->name('allProductCollection');

    Route::get('/flash-deal', 'allFlashDealProduct')->name('allFlashDealProduct');
    Route::get('/everyday-low-price', 'allEverydayLowPriceProduct')->name('allEverydayLowPriceProduct');
    Route::get('/flash-sale', 'allFlashSaleProduct')->name('allFlashSaleProduct');
    Route::get('/fashion', 'allFashionProduct')->name('allFashionProduct');
    Route::get('/order-track','orderTrack')->name('order.track');
    Route::post('/order-track','orderTrackStore');
});

Route::controller(CartController::class)->group(function () {
    //cart
    Route::get('/cart', 'cart')->name('cart');
    Route::post('/add-to-cart', 'addToCart');
    Route::post('/update-cart', 'updateCart')->name('updateCart');
    Route::get('/remove-from-cart/{rowId}', 'removeFromCart')->name('removeFromCart');
    Route::get('/destroy-cart', 'destroyCart')->name('destroyCart');

    //coupon
    Route::post('/apply-coupon', 'applyCoupon')->name('applyCoupon');
    Route::get('/remove-coupon', 'removeCoupon')->name('removeCoupon');
});
Route::post('/add-to-wishlist', [WishlistController::class, 'addToWishlist']);
Route::post('/add-voucher', [CartController::class, 'applyVoucher']);
Route::middleware('auth')->group(function () {
    //rating and review
    Route::post('/store-rating-review', [RatingReviewController::class, 'storeRatingReview'])->name('storeRatingReview');
    //user dashboard
    Route::get('/user/dashboard', [FrontendController::class, 'dashboard'])->name('user.dashboard');

    //wishlist
    Route::get('/wishlist', [WishlistController::class, 'wishlist'])->name('wishlist');

    Route::get('/remove-from-wishlist/{id}', [WishlistController::class, 'removeFromWishlist'])->name('removeFromWishlist');

    //user profile
    Route::get('/user-profile', [ProfileController::class, 'showProfile'])->name('showProfile');
    Route::post('/store-user-profile/{id}', [ProfileController::class, 'storeProfile'])->name('storeProfile');

    //checkout
    Route::get('/checkout', [CheckoutController::class, 'checkout'])->name('checkout');

    //adding shipping charge by ajax request
    Route::post('/add-shipping-charge', [CartController::class, 'addshippingCharge']);

    //place order
    Route::post('/place-order', [OrderController::class, 'placeOrder'])->name('placeOrder');
    Route::get('/order-history', [OrderController::class, 'customerOrderHistory'])->name('orderHistory');
    Route::post('/cancel-order/{id}', [OrderController::class, 'customerCancelOrder'])->name('cancelOrder');
    Route::get('/user-invoice/{id}', [OrderController::class, 'customerInvoice'])->name('invoice');

});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

//backend
Route::prefix('/admin')->name('admin.')->middleware('guest:admin')->group(function () {
    Route::get('/login', [AdminLoginController::class, 'login'])->name('login');
    Route::post('/store-login', [AdminLoginController::class, 'storeLogin'])->name('storeLogin');
});

Route::prefix('/admin')->as('admin.')->middleware('auth:admin')->group(function () {
    Route::post('/logout', [AdminLoginController::class, 'logout'])->name('logout');

    Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');

    //admin management
    Route::controller(AdminRegistrationController::class)->middleware('admin_user')->group(function () {
        Route::get('/admin-list', 'adminList')->name('adminList');
        Route::get('/create-admin', 'createAdmin')->name('createAdmin');
        Route::post('/store-admin', 'storeAdmin')->name('storeAdmin');
        Route::get('/edit-admin/{admin}', 'editAdmin')->name('editAdmin');
        Route::post('/update-admin/{admin}', 'updateAdmin')->name('updateAdmin');
        Route::post('/admin/active-admin/{admin}', 'activeAdmin')->name('activeAdmin');
        Route::post('/admin/inactive-admin/{admin}', 'inactiveAdmin')->name('inactiveAdmin');
        Route::delete('/delete-admin/{admin}', 'deleteAdmin')->name('deleteAdmin');

        Route::get('/customer-list', 'customerList')->name('customerList');
    });
    Route::middleware('main_menu')->group(function () {
        //slider
        Route::controller(SliderController::class)->group(function () {
            Route::get('/slider', 'allSlider')->name('allSlider');
            Route::get('/create-slider', 'createSlider')->name('createSlider');
            Route::post('/store-slider', 'storeSlider')->name('storeSlider');
            Route::get('/edit-slider/{slider}', 'editSlider')->name('editSlider');
            Route::put('/update-slider/{slider}', 'updateSlider')->name('updateSlider');
            Route::delete('/delete-slider/{slider}', 'deleteSlider')->name('deleteSlider');
        });

        //main menu
        //category
        Route::controller(CategoryController::class)->group(function () {
            Route::get('/category', 'category')->name('category');
            Route::get('/create-category', 'createCategory')->name('createCategory');
            Route::post('/store-category', 'storeCategory')->name('storeCategory');
            Route::get('/edit-category/{id}', 'editCategory')->name('editCategory');
            Route::patch('/update-category/{id}', 'updateCategory')->name('updateCategory');
            Route::post('/active-category/{id}', 'activeCategory')->name('activeCategory');
            Route::post('/inactive-category/{id}', 'inactiveCategory')->name('inactiveCategory');
        });

        //subcategory
        Route::controller(SubcategoryController::class)->group(function () {
            Route::get('/subcategory', 'subcategory')->name('subcategory');
            Route::get('/create-subcategory', 'createSubcategory')->name('createSubcategory');
            Route::post('/store-subcategory', 'storeSubcategory')->name('storeSubcategory');

app/Http/Controllers/Backend/BannerCollectionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\BannerCollection;
use App\Models\Subcategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;

class BannerCollectionController extends Controller {
    public function bannerCollection() {
        $banner = BannerCollection::find(1);
        $sub    = Subcategory::where('status', 1)->get();

        return view('backend.banner-collection', compact('banner', 'sub'));
    }

    public function storeBannerCollection(Request $request) {
        $validator = Validator::make($request->all(), [
            'image'             => 'nullable|image|mimes:jpeg,png,jpg,gif',
            'banner_collection' => 'required',
            'status'            => 'required',
        ]);

        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all())->withInput();
        }

        BannerCollection::updateOrcreate(
            ['id' => 1],
            [
                'banner_collection' => $request->banner_collection,
                'status'            => $request->status,
            ]
        );

        if ($request->hasFile('image')) {

            $image_file = $request->file('image');

            if ($image_file) {
                $banner = BannerCollection::where('id', 1)->first()->image ?? '';

                if ($banner) {
                    $image_path = public_path($banner);

                    if (File::exists($image_path)) {
                        File::delete($image_path);
                    }

                }

                $img_gen   = hexdec(uniqid());
                $image_url = 'images/banner_collection/';
                $image_ext = strtolower($image_file->getClientOriginalExtension());

                $img_name    = $img_gen . '.' . $image_ext;
                $final_name1 = $image_url . $img_gen . '.' . $image_ext;

                $image_file->move($image_url, $img_name);
                BannerCollection::updateOrcreate(
                    ['id' => 1],
                    [
                        'image' => $final_name1,
                    ]
                );
            }

        }

        return redirect()->back()->withToastSuccess('Banner collection store successfully!!');
    }

    public function activeBannerCollection(Request $request, $id) {
        $banner = BannerCollection::findOrFail($id);

        $banner->status = 1;
        $banner->save();

        return redirect()->route('admin.bannerCollection')->withToastSuccess('Banner Collection Activated Successfully!!');

    }

    public function inactiveBannerCollection(Request $request, $id) {
        $banner = BannerCollection::findOrFail($id);

        $banner->status = 0;
        $banner->save();

        return redirect()->route('admin.bannerCollection')->withToastSuccess('Banner Collection Inactivated Successfully!!');

    }

}

app/Http/Controllers/Backend/ColorController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Color;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ColorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $colors = Color::withCount('products')->get();

        return view('backend.color.index', compact('colors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('backend.color.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $validator = Validator::make($request->all(), [
            'color_code'   => 'required|unique:colors',
            'color_code.*' => 'required',
            'color'        => 'required|unique:colors',
            'color.*'      => 'required',
        ]);

        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all())->withInput();
        }

        foreach ($request->input('color') as $key => $f) {
            Color::create(['color_code' => $request->color_code[$key], 'color' => $request->color[$key]]);
        }

        return redirect()->route('admin.colors.index')->withToastSuccess('Colors Added Successfully!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Color $color) {
        return view('backend.color.edit', compact('color'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Color $color) {
        $validator = Validator::make($request->all(), [
            'color_code' => 'required|unique:colors,color_code,' . $color->id,
            'color' => 'required|unique:colors,color,' . $color->id,
        ]);

        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all())->withInput();
        }

        $color->update($request->all());

        return redirect()->route('admin.colors.index')->withToastSuccess('Colors Updated Successfully!!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Color $color) {
        $color->delete();

        return redirect()->route('admin.colors.index')->withToastSuccess('Colors Deleted Successfully!!');

    }

}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use App\Models\Order;
use App\Models\Product;
use App\Models\User;

class DashboardController extends Controller {
    public function dashboard() {
        $data                        = [];
        $data['todays_order']        = Order::where('created_at', today())->count();
        $data['todays_cancel_order'] = Order::where('created_at', today())->where('status', 0)->count();
        $data['cancel_order']        = Order::where('status', 0)->count();
        $data['pending_order']       = Order::where('status', 1)->count();
        $data['confirm_order']       = Order::where('status', 2)->count();
        $data['shipped_order']       = Order::where('status', 3)->count();

        $data['active_product']   = Product::where('status', 1)->count();
        $data['inactive_product'] = Product::where('status', 0)->count();

        $data['customer'] = User::count();
        $data['admin']    = Admin::count();

        return view('backend.dashboard', $data);
    }
}

app/Http/Controllers/Backend/FlashSaleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\FlashSale;
use Illuminate\Http\Request;

class FlashSaleController extends Controller {
    public function flashSaleTimer() {
        $flash = FlashSale::find(1);

        return view('backend.flash-sale-timer', compact('flash'));
    }

    public function storeFlashSaleTimer(Request $request) {
        FlashSale::updateOrCreate(
            ['id' => 1],
            [
                'end' => $request->end,
            ]
        );

        return redirect()->back();
    }
}

resources/views/backend/order/cancel-order.blade.php
@extends('backend.layouts.master')
@section('title', 'Canceled Order List')
@section('cssLink')
@endsection
@section('cssStyle')
@endsection

@section('backend')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Canceled Order</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active">Canceled Order</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">

                            @foreach ($orders as $order)
                                <h4>Order: #{{ $order->id }} || Total Price: ৳{{ $order->total_price }} || Date:
                                    {{ $order->created_at }}</h4>
                                <table id="" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>SL.</th>
                                            <th>Product Name</th>
                                            <th>Product Quantity</th>
                                            <th>Product Unit Price</th>
                                            <th>Status</th>
                                            <th>Created_at</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($order->orderProducts as $key => $product)
                                            <tr>
                                                <td>{{ ++$key }}</td>
                                                <td>{{ $product->prod->name }}</td>
                                                <td>{{ $product->qty }}</td>
                                                <td>{{ $product->unit_price }}</td>
                                                <td class="text-danger">Canceled</td>
                                                <td>{{ $product->created_at }}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                <br>
                                <hr>
                                <br>
                            @endforeach
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@section('jsLink')
@endsection
@section('jsScript')
@endsection

resources/views/backend/order/confirm-order.blade.php
@extends('backend.layouts.master')
@section('title', 'Confirmed Order List')
@section('cssLink')
@endsection
@section('cssStyle')
@endsection

@section('backend')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Confirmed Order</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active">Confirmed Order</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">

                            @foreach ($orders as $order)
                                <h4>Order: #{{ $order->id }} || Total Price: ৳{{ $order->total_price }} || Date:
                                    {{ $order->created_at }}</h4>
                                @if ($order->status == 2)
                                    <div class="d-flex justify-content-start>">
                                        <form action="{{ route('admin.orderShippedForCustomer', $order->id) }}"
                                            method="post">
                                            @csrf
                                            <button type="submit"
                                                onclick="return(confirm('Are you sure want to Shipped this item?'))"
                                                class="btn btn-success btn-sm"> Shiped Order
                                            </button>
                                        </form>

                                        <a href="{{ route('admin.invoice', $order->id) }}" class="btn btn-info btn-sm">
                                            Invoice </a>
                                    </div>
                                @endif
                                <table id="" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>SL.</th>
                                            <th>Product Name</th>
                                            <th>Product Quantity</th>
                                            <th>Product Unit Price</th>
                                            <th>Status</th>
                                            <th>Created_at</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($order->orderProducts as $key => $product)
                                            <tr>
                                                <td>{{ ++$key }}</td>
                                                <td>{{ $product->prod->name }}</td>
                                                <td>{{ $product->qty }}</td>
                                                <td>{{ $product->unit_price }}</td>
                                                <td>Confirmed</td>
                                                <td>{{ $product->created_at }}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                <br>
                                <hr>
                                <br>
                            @endforeach
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@section('jsLink')
@endsection
@section('jsScript')
@endsection

resources/views/backend/order/shipped-order.blade.php
@extends('backend.layouts.master')
@section('title', 'Shipped Order List')
@section('cssLink')
@endsection
@section('cssStyle')
@endsection

@section('backend')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Shipped Order</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active">Shipped Order</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">

                            @foreach ($orders as $order)
                                <h4>Order: #{{ $order->id }} || Total Price: ৳{{ $order->total_price }} || Date:
                                    {{ $order->created_at }}</h4>
                                @if ($order->status === 3)
                                    <div class="d-flex justify-content-start>">
                                        <a href="{{ route('admin.invoice', $order->id) }}" class="btn btn-info btn-sm">
                                            Invoice </a>
                                    </div>
                                @endif
                                <table id="" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>SL.</th>
                                            <th>Product Name</th>
                                            <th>Product Quantity</th>
                                            <th>Product Unit Price</th>
                                            <th>Status</th>
                                            <th>Created_at</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($order->orderProducts as $key => $product)
                                            <tr>
                                                <td>{{ ++$key }}</td>
                                                <td>{{ $product->prod->name }}</td>
                                                <td>{{ $product->qty }}</td>
                                                <td>{{ $product->unit_price }}</td>
                                                <td>Pending</td>
                                                <td>{{ $product->created_at }}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                <br>
                                <hr>
                                <br>
                            @endforeach
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@section('jsLink')
@endsection
@section('jsScript')
@endsection